MusimatLib: /Users/garethloy/Musimathics/Musimat1.2/MusimatLib/Random.cpp File Reference
/Users/garethloy/Musimathics/Musimat1.2/MusimatLib/Random.cpp File Reference
#include <time.h>
#include "Musimat.h"
Functions
Integer LCRandom ()
Didactic wrapper for lCRandom method.
Real Random (Real L, Real U)
Didactic wrapper for random method.
Integer Random (Integer L, Integer U)
Integer didactic wrapper for random method.
Integer IRandom (Integer L, Integer U)
Didactic wrapper for Integer random method.
Integer SeedRandom (Integer seed)
Didactic wrapper for seed method.
Integer Time ()
Return elapsed seconds since epoch.
Variables
Static class Random ran
Function Documentation
Integer IRandom (Integer L, Integer U)
Didactic wrapper for Integer random method.
Definition at line 32 of file Random.cpp.
References ran, Random::random(), and Return.
Referenced by RandomRow(), and randTendency().
{
        Return ran.random( L, U );
}
Integer LCRandom ()
Didactic wrapper for lCRandom method.
Definition at line 20 of file Random.cpp.
References Random::lCRandom(), ran, and Return.
{ Return ran.lCRandom(); }
Real Random (Real L, Real U)
Didactic wrapper for random method.
Definition at line 22 of file Random.cpp.
References ran, Random::random(), and Return.
{
        Return ran.random( L, U );
}
Integer Random (Integer L, Integer U)
Integer didactic wrapper for random method.
Definition at line 27 of file Random.cpp.
References ran, Random::random(), and Return.
{
        Return ran.random( L, U );
}
Integer SeedRandom (Integer seed)
Didactic wrapper for seed method.
Definition at line 37 of file Random.cpp.
References ran, Return, and Random::seed().
{
        Return ran.seed( seed );
}
Integer Time ()
Return elapsed seconds since epoch.
Get the elapsed seconds since the epoch by calling system time function.
Definition at line 47 of file Random.cpp.
References Random::getTime(), ran, and Return.
{
        Return ran.getTime();
}
Variable Documentation
Static class Random ran
Definition at line 18 of file Random.cpp.
Referenced by IRandom(), LCRandom(), Random(), SeedRandom(), and Time().