MusimatLib: List Length Functions
List Length Functions
Length of the appropriate type List.
Functions
Integer Length (RhythmList Reference L)
Length of a ComplexList.
Integer Length (String s)
String length.
Detailed Description
Length of the appropriate type List.
Function Documentation
Integer Length (RhythmList Reference L)
Length of a ComplexList.
Parameters:
L ComplexList
Integer Length (String s)
String length.
Parameters:
s String
Returns:
The length of the String
Definition at line 23 of file Musimat.cpp.
References Return.
Referenced by cycle(), IntegerListToPitchList(), Map(), permute(), PitchListToIntegerList(), RealListToRationalList(), SetComplex(), shuffle(), and stretch().
{ Return(Integer(strlen(s)+1)); }