Musimat Chapter 9 Code Examples: /Users/garethloy/Musimathics/Musimat1.2/MusimatChapter9/MusimatChapter9.cpp File Reference
/Users/garethloy/Musimathics/Musimat1.2/MusimatChapter9/MusimatChapter9.cpp File Reference
#include "stdafx.h"
#include <iostream>
#include "MusimatChapter9.h"
Functions
int _tmain (int argc, _TCHAR *argv[])
Function Documentation
int _tmain (int argc, _TCHAR * argv[])
Definition at line 55 of file MusimatChapter9.cpp.
References C090400(), C090703(), C090703a(), C090703b(), C090703c(), C090903(), C091101(), C091102(), C091200(), C091201(), C091201a(), C091201b(), C091201c(), C091201d(), C091201e(), C091201f(), C091204(), C091204a(), C091204b(), C091204d(), C091405(), C091406(), C091406a(), C091406b(), C091406c(), C091704b(), C091704c(), and C091704d().
{
        // Plant your first breakpoint on the line below containing
        // C090400().  Then run the program, which will stop just
        // before executing that function.  To start, use the
        // debugger's "step into" command to step into the function.
        C090400();      // 9.4 Program for Guido's Method
        // When you get here, you've finished stepping through C090400().
        // To continue, use the debugger's "step into" command to
        // step into the next function.
        C090703();      // 9.7.3 Linear Congruential Method
        // Use the debugger's "step into" command to continue
        // by stepping into each of the following functions.
        // For some sections, there may be additional functions for you
        // to visit within each file.
        C090400();      // Program for Guido's Method
        C090703a();     // Seeding the Random Number Generator
        C090703b();     // Random Real Numbers
        C090703c();     // Random Integer Numbers Scaled to an Arbitrary Range
        C090903();      // 9.9.3 Circular Permutation
        C091101();      // 9.11.1 Precomposition
        C091102();      // 9.11.2 The Set Complex
        C091200();      // 9.12 Traversing and Manipulating Musical Materials
        C091201();      // 9.12.1 Deterministic Serial Methods
        C091201a();     // Cycle
        C091201b();     // Palindrome
        C091201c();     // Permutation
        C091201d();     // Transpose
        C091201e();     // Interpolated Tendency Mask
        C091201f();     // Linear Interpolation
        C091204();      // 9.12.4 Nondeterministic Serial Methods
        C091204a();     // Sampling without Replacement
        C091204b();     // Shuffle
        C091204d();     // Random Tendency Mask
        C091405();      // 9.14.5 Generating Outcomes from Probability Distributions
        C091406();      // 9.14.6 Cumulative Distribution Function
        C091406a();     // Accumulation
        C091406b();     // Traversing the Cumulative Distribution Function
        C091406c();     // A Less Boring (?) Musical Example
        C091704b();     // Brownian Nose Generator
        C091704c();     // Fractional Brownian Motion
        C091704d();     // Voss's Method
        Return 0;
}