Musimat Tutorial: /Users/garethloy/Musimathics/Musimat1.2/MusimatTutorial/B0201c.cpp File Reference
/Users/garethloy/Musimathics/Musimat1.2/MusimatTutorial/B0201c.cpp File Reference
#include "MusimatTutorial.h"
Functions
MusimatTutorialSection (B0201c)
RealList naturalChromatic (1.0/1.0, 16.0/15.0, 9.0/8.0, 6.0/5.0, 5.0/4.0, 4.0/3.0, 64.0/45.0, 3.0/2.0, 8.0/5.0, 5.0/3.0, 16.0/9.0, 15.0/8.0)
Static Void para1 ()
Variables
Real R = 440.0
Real cNat4 = R * 3.0/5.0
Function Documentation
MusimatTutorialSection (B0201c)
Definition at line 2 of file B0201c.cpp.
References para1().
{
        Print("*** Natural Chromatic Scale ***");
        /*****************************************************************************
         Natural Chromatic Scale
         To create the natural chromatic scale, all we need now is to establish
         the frequency reference for natural chromatic middle C and tabulate the ratios of the scale.
         *****************************************************************************/
        para1();  // Step into this function to continue the tutorial
}
RealList naturalChromatic (1.0/1. 0, 16.0/15. 0, 9.0/8. 0, 6.0/5. 0, 5.0/4. 0, 4.0/3. 0, 64.0/45. 0, 3.0/2. 0, 8.0/5. 0, 5.0/3. 0, 16.0/9. 0, 15.0/8. 0)
Static Void para1 ()
Definition at line 23 of file B0201c.cpp.
References cNat4, naturalChromatic(), and pitchToHz().
                    {
        /*****************************************************************************
         Then
         *****************************************************************************/
        Print("A4=",  pitchToHz(A4 , cNat4, naturalChromatic));
        /*****************************************************************************
         prints A4=440.0, and
         *****************************************************************************/
        Print("C4=",  pitchToHz(C4 , cNat4, naturalChromatic));
        /*****************************************************************************
         prints C4=264.00.
         *****************************************************************************/
}
Variable Documentation
Real cNat4 = R * 3.0/5.0
Definition at line 15 of file B0201c.cpp.
Real R = 440.0
Definition at line 14 of file B0201c.cpp.